// Cart
const ADD_TO_CART = 'ADD_TO_CART';
const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
const INCREMENT_AMOUNT = 'INCREMENT_AMOUNT';
const DECREMENT_AMOUNT = 'DECREMENT_AMOUNT';

// Favorites
const ADD_TO_FAVORITES = 'ADD_TO_FAVORITES';
const REMOVE_FROM_FAVORITES = 'REMOVE_FROM_FAVORITES';

export {
    ADD_TO_CART,
    REMOVE_FROM_CART,
    INCREMENT_AMOUNT,
    DECREMENT_AMOUNT,
    ADD_TO_FAVORITES,
    REMOVE_FROM_FAVORITES
};